version: '3.8'

services:
  # Serviço PHP-FPM
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: facebug_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - facebug_network
    depends_on:
      - mysql
      - redis

  # Servidor Web Nginx
  nginx:
    image: nginx:alpine
    container_name: facebug_nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
      - ./docker/nginx/ssl:/etc/nginx/ssl
    networks:
      - facebug_network
    depends_on:
      - app

  # Banco de Dados MySQL
  mysql:
    image: mysql:8.0
    container_name: facebug_mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - facebug_network

  # Redis para Cache
  redis:
    image: redis:alpine
    container_name: facebug_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - facebug_network

# Redes Docker
networks:
  facebug_network:
    driver: bridge

# Volumes persistentes
volumes:
  mysql_data:
    driver: local
  redis_data:
    driver: local